---
title: "About"
links:
    - icon: twitter
      text: twitter
      href: https://x.com/IluAhmad_
    - icon: github
      text: Github
      href: https://github.com/Iluahmad
    - icon: envelope
      text: Email
      href: iluahmad7@yahoo.com
editor: 
  markdown: 
    wrap: 72
---

I am Ahmad Ibraheem Ilu born and raised in Kano,
Nigeria. I had all my previous education here in Nigeria, Undergraduate
training at Northwest University Kano, and Postgraduate Studies to
obtain M.Sc in Economics at Bayero University, Kano. I am currently an
Economist at the Nigerian Economic Summit Group (NESG), the First and
Foremost Think-Tank in Nigeria. Alongisde my routine engagements at the
NESG, I am part of the NESG Five men delegation sitting at the Ongoing
Presidential Fiscal Policy and Tax Reforms Commitee (PFPTR), a commitee
inaugruated in August, 2023 by the President Federal Republic of Nigeria
to oversee systemic Fiscal Policy and Tax reforms in Nigeria. I was
previosuly an Assistant Lecturer at the Department of Economics at the
Federal University Dutsin-Ma, Katsina State, Nigeria. Right from the
onset, I am very fortunate to know for sure that Economics is my passion
and that an academic career is the best path for me. In hindsight, it
seems clear that I had from the beginning the traits of a good
researcher. Being inquisitive and being always eager to ask questions
and to learn has helped in distinguishing myself from school throughout
my Bachelor's and Masters. I am fascinated by Economics, providing an
understanding of human action without losing formal rigor. During my
undergraduate coursework, I graduated as one of the top 5 graduating
students with consistency to average above 4.0 GPA out of the 5.0 Scale
in all of the eight semesters attended. 

Majorly, during my B.SC and M.SC, I was determined to specialize in
Macroeconomics related areas, i.e Monetary Economics, International
Economics, Financial Economics, etc. My passion for Macroeconomics made
me a little popular in my neighborhood and my social media community
(Twitter and Facebook) where lots of people usually solicit my personal
opinion whenever there is a socioeconomic debate on recent Government
policies. This has allowed local TV stations to invite me as a guest
speaker to Proffer commentaries and analysis on contemporary
macroeconomic and public policies in Nigeria on their scheduled
economy-related program. My intense passion for research and academics,
motivated me to author four academic papers all of which are published
in an open-access repository, the web links of all documents are
detailed in my C.V. The Research Papers are

-   Impact of Remittances from Nigerians in diaspora on Exchange Rate
    Stability (2019).

-    Analysis of the nexus between environmental quality and economic
    growth (2019).

-   Oil Price Volatility and Exchange Rate Dynamics (2019).

-    Exchange Pass-Through to Stock Prices: A Multi -GARCH
    Approach(2020).

Also given my enthusiasm and zeal toward research in Economics, I have
been to steadfastly determined to equip myself with global
best-practicing research techniques and software such as R programming
language using Rstudio (now, "Posit") R-markdown, Latex, Stata, Eviews,
GitHub, Matlab and Dynare in a view to boost my research efficacy and
Prowess.

During my Master's program at Bayero University Kano (BUK), a top
University in Nigeria, I learned the core tools used in modern economic
research: Macro and Microeconomics theory, Statistics, Econometrics, and
advanced math (including Linear Algebra, Matrix Algebra, Differential
Equations, Difference Equations, Eigen Vectors, and Eigen Values,
Dynamic Optimization; Calculus of Variation, Optimal Control, and DSGE
Modelling; Representative Agent Model, Overlapping Generation Model and
the likes of RBC variant Models ), all following the standard practice
on the top departments in the world. Modelling the general equilibrium
of an economy usually falls under the framework of Dynamic Stochastic
General Equilibrium (DSGE) based Models which encapsulates rigorous
mathematical tools such as the multivariate calculus; differential
equation, difference equations, Optimal control theory, Bellman
equations( recursive method) and Lagrangian optimization (Sequential
methods ). I also took elective courses related to my main interests:
Monetary economics, Financial economics, and International trade. This
reiterates my genuine desire to stay in academia, research and policy. I have written my Dissertation on the "ANALYSIS OF KEY DETERMINANTS OF EXCHANGE RATE
STABILITY IN NIGERIA" Via the Auto-regressive Distributed Lag model
(ARDL) using Nigeria's time-series data. I also have experience as a
Graduate Assistant and Assistant Lecturer; teaching various
undergraduate courses and supervising dissertations at the Federal
University of Dutsin-Ma.

