%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Ahmad Ilu\Desktop\PC\Lenovo 2023\ACCER 2020\RESEARCH COLLECTION\Latex Practice\Energy Conference\Energy Data.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 10-Sep-2024 01:07:36

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:E176";

% Specify column names and types
opts.VariableNames = ["Year", "Month", "ExchangeRate", "InflationRate", "PMS"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
EnergyData = readtable("C:\Users\Ahmad Ilu\Desktop\PC\Lenovo 2023\ACCER 2020\RESEARCH COLLECTION\Latex Practice\Energy Conference\Energy Data.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts