---
title: "Agriculutural Global Value Chains (GVCs)"
subtitle: "A Sample Beamer Document Using Rmarkdwon"
author: "Mr. Ahmad Ilu"
institute: "Finnmetrics"
theme: "Madrid"
date: "2/11/2022"
tittlegraphic: "Finmetrics"
output: beamer_presentation
bibliography: ["dattijo.bib"]
---

# Economics

Despite a rebound in global economic growth,the @Flagship_2022 flagship report, reveals that an estimated $5.5\%$ global growth rate was recorded in 2021, in comparison to the peak pandemic levels, this is a clear macroeconomic improvement. However, the same report, postulated that the global economy is expected to decelerate to $4.1\%$ citing the potential implications of continued COVID-19 flare-ups, diminished fiscal support, and lingering supply bottlenecks. The short-term outlook for global growth is somewhat weaker, and global inflation evidently higher than previously envisioned, owing to pandemic resurgence, higher food and energy prices, and more pernicious supply disruptions, these led to projected shrinking of global growth to 3.2 percent 2023. In contradiction to the global economy trend, growth in Sub-Saharan Africa (SSA) reached an estimated 3.5 percent in 2021, this is propagated by a rebound in commodity prices and a gradual easing of social restrictions. Growth is projected to averagely revolved around to $3.7\%$ in 2022-23. Agriculture in Africa has an immense social and economic footprint, about $60\%$ of the population of sub-Saharan Africa is smallholder farmers, security. Data from the World Bank shows that sub-Saharan Africa has an estimated GDP of $\$1.7$ trillion,with agriculture accounting for just under $\$300 billion$ ($17\%$ of the economy) while employing 282 million people (equivalent to $51\%$ of total employment) comes from agriculture. Despite the numbers, Africa's full agricultural potential remains untapped and not optimally utilized. In their recent analysis @Mckinsey2019, concluded that Africa could produce two to three times more cereals and grains which would add $20\%$ more cereals and grains to the current worldwide 2.6 billion tons of output. However, this would require a further significant investment. The study further analyzed productivity potential across 44 countries in sub-Saharan Africa, that majorly nine countries make up $60\%$ of the total potential, with three countries (Ethiopia, Nigeria, and Tanzania) leading the growth and capable of producing $50\%$ out of the total increment. Developing the agricultural sector is also central to economic diversification in several SSA countries, i.e., Angola and Nigeria @Chatterjee_2014.\\ GVCs have notably become a dominant feature of world trade and investment encompassing both developing and developed economies. The process involved in value chains (VCs) including producing goods ranging from sourcing of raw materials to finished products are increasingly fragmented and earned out wherever the necessary skills and materials are sufficiently available at a competitive cost and quality. Businesses focus on what they do best in their home markets and outsource the rest. In developing countries, the expansion and integration of global value chain participation of agriculture and food sectors could support transformation from a subsistence-based and to a commercialized, productive and off-farm system. Trade liberalization ha s been observed as a means to foster growth and welfare. However, it has narrowed the policy options for developing economies, thereby making protection of their industries increasingly difficult. Version 2020's World Development Report (WDR) defines GVCs as the series of stages in the production of a product or service for sale to consumers. Each stage adds value, and at least two stages are in different countries.

# Finance

Despite a rebound in global economic growth,the @Flagship_2022 flagship report, reveals that an estimated $5.5\%$ global growth rate was recorded in 2021, in comparison to the peak pandemic levels, this is a clear macroeconomic improvement. However, the same report, postulated that the global economy is expected to decelerate to $4.1\%$ citing the potential implications of continued COVID-19 flare-ups, diminished fiscal support, and lingering supply bottlenecks. The short-term outlook for global growth is somewhat weaker, and global inflation evidently higher than previously envisioned, owing to pandemic resurgence, higher food and energy prices, and more pernicious supply disruptions, these led to projected shrinking of global growth to 3.2 percent 2023. In contradiction to the global economy trend, growth in Sub-Saharan Africa (SSA) reached an estimated 3.5 percent in 2021, this is propagated by a rebound in commodity prices and a gradual easing of social restrictions. Growth is projected to averagely revolved around to $3.7\%$ in 2022-23.

# Metrics

Despite a rebound in global economic growth,the @Flagship_2022 flagship report, reveals that an estimated $5.5\%$ global growth rate was recorded in 2021, in comparison to the peak pandemic levels, this is a clear macroeconomic improvement. However, the same report, postulated that the global economy is expected to decelerate to $4.1\%$ citing the potential implications of continued COVID-19 flare-ups, diminished fiscal support, and lingering supply bottlenecks. The short-term outlook for global growth is somewhat weaker, and global inflation evidently higher than previously envisioned, owing to pandemic resurgence, higher food and energy prices, and more pernicious supply disruptions, these led to projected shrinking of global growth to 3.2 percent 2023. In contradiction to the global economy trend, growth in Sub-Saharan Africa (SSA) reached an estimated 3.5 percent in 2021, this is propagated by a rebound in commodity prices and a gradual easing of social restrictions. Growth is projected to averagely revolved around to $3.7\%$ in 2022-23.

# References
